import raccoon

raccoon.go_up()
raccoon.go_left(3)
raccoon.go_right(6)
raccoon.go_left(3)
raccoon.go_up(2)
raccoon.go_left(2)
raccoon.go_right(4)
raccoon.go_left(2)
raccoon.go_up(2)
raccoon.go_left()
raccoon.go_right(2)
raccoon.go_left()
raccoon.go_up()