import raccoon

raccoon.go_up(5)
raccoon.go_down(2)
raccoon.go_right(2)
raccoon.wait()
raccoon.go_right()
raccoon.go_left(3)
raccoon.go_down(2)
raccoon.go_right(3)
raccoon.go_down()
raccoon.go_up()
raccoon.go_right()
raccoon.wait(3)
raccoon.go_right()
raccoon.set_mine()
raccoon.go_left()
raccoon.wait(4)
raccoon.go_right()
raccoon.go_up(4)